language: node_js
node_js:
  - 5.8.0

before_install:
  - mkdir -p $HOME/bin $HOME/lib2 $HOME/lib
  - test -x ./node_modules/.bin/npm || npm install npm@2.15.0
  - test -d ./node_modules && cp -rpf ./node_modules $HOME/lib2/ || true
  - ln -sf ../lib2/node_modules/qnit/bin/qnit $HOME/bin/qnit
  - ln -sf ../lib2/node_modules/npm/bin/npm-cli.js $HOME/bin/npm2
  - npm2 --version
  - npm2 install .
  - nvm install 0.8.28 && npm2 -v && node -v && npm2 test
  - nvm install 0.10 && npm2 -v && node -v && npm2 test
  - nvm install 4 && npm2 -v && node -v && npm2 test
  - nvm install 6 && npm2 -v && node -v && npm2 test
  - nvm install 8 && npm2 -v && node -v && npm2 test
  - nvm install 12 && npm2 -v && node -v && npm2 test
  - nvm install 16 && npm2 -v && node -v && npm2 test
  - nvm install 5.8.0

after_success:
  - npm install -g nyc@8.4.0 coveralls@3.0.2 codecov
  - npm run coverage && codecov
  - nyc report -r text-lcov | coveralls
