name: nodejs ci
on:
  push:
    branches: [ $default-branch, ar-test ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 5.8.0, 6.x, 10.x, 12.x, 16.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm install -g qnit npm@2.15.0
      - run: npm test

      - if: ${{ matrix.node == '5.8.0' }}
        name: Check code coverage
        run: npm install -g nyc@8.4.0
        run: npm run coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
